import { verifyPresentation } from "did-jwt-vc"

export * from "./create-credential"
export * from "./create-presentation"
export * from "./is-credential"
export * from "./signing/sign-credential"
export * from "./signing/sign-presentation"
export * from "./types"
export * from "./revocation/make-revocable"
export * from "./revocation/status-list-credential"
export * from "./revocation/types"
export * from "./verification/errors"
export * from "./verification/is-expired"
export * from "./verification/is-revoked"
export * from "./verification/types"
export * from "./verification/parse-jwt-credential"
export * from "./verification/verify-parsed-credential"
export * from "./verification/verify-proof"

export { verifyPresentation }
